import { int, sqliteTable, text } from 'drizzle-orm/sqlite-core';
import { usersTable } from '@/server/db/tables/user';
import { sql } from 'drizzle-orm';

export const shoppingSessionsTable = sqliteTable('shopping_sessions', {
    id: int('id').primaryKey({ autoIncrement: true }).notNull(),
    ownerId: int('owner_id').notNull().references(() => usersTable.id, { onDelete: 'cascade' }),
    name: text('name'),
    createdAt: int('created_at', { mode: 'timestamp_ms' }).notNull().default(sql`CURRENT_TIMESTAMP`),
    autoGenerated: int('auto_generated', { mode: 'boolean' }).notNull().default(sql`0`),
});