import type { InferSelectModel } from 'drizzle-orm';
import { createInsertSchema } from 'drizzle-zod';
import { shoppingSessionsTable } from '@/server/db/tables/shopping_session';
import { sessionTransactionsTable } from '@/server/db/tables/session_transaction';
import { z } from 'zod';

export type ShoppingSession = InferSelectModel<typeof shoppingSessionsTable>;
export type SessionTransaction = InferSelectModel<typeof sessionTransactionsTable>;

export const ShoppingSessionCreateSchema = createInsertSchema(shoppingSessionsTable)
    .omit({ ownerId: true, autoGenerated: true, createdAt: true })
    .extend({
        transactionIds: z.array(z.number()),
    });

export const ShoppingSessionUpdateSchema = z.object({
    id: z.number(),
    name: z.string().optional(),
    addTransactionIds: z.array(z.number()).optional(),
    removeTransactionIds: z.array(z.number()).optional(),
});